### ISSUE TITLE
mqtt got "Detected XCPU in the GDB loop (0x9db00000)"

### ISSUE THREAD

**Issue by ningpeng** [Ai-Thinker-Open/GPRS_C_SDK#37]
Tracer GUI loaded.
TRACE SNIFFING ON.
Detected XCPU in the GDB loop (0x9db00000), connect GDB debugger for more info.
Detected BCPU in the GDB loop (0x9db10000), connect GDB debugger for more info.

code : the lastest of the master ( 01/01/2018 ) ( didn't change any code )
$ ./build.sh demo mqtt  

gdb info 
(gdb) bt
#0  0x882401d5 in OnPublish ()
#1  0x8816406d in ?? ()

[20:34:36.099]   AT 01  : TaskName: CFW -- inet_chksum_pseudo(): checksumming pbuf 0x82129698 (has next 0x0)
[20:34:36.099]   AT 01  : TaskName: CFW -- inet_chksum_pseudo(): pbuf chain lwip_chksum()=702
[20:34:36.099]   AT 01  : TaskName: CFW -- pbuf_header: old 0x821296e0 new 0x821296cc (20)
[20:34:36.099]   AT 01  : TaskName: CFW -- ip4_output_if: GP0
[20:34:36.104]   AT 01  : TaskName: CFW -- IP header:
[20:34:36.104]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.104]   AT 01  : TaskName: CFW -- | 4 | 5 |  0x00 |        44     | (v, hl, tos, len)
[20:34:36.104]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.104]   AT 01  : TaskName: CFW -- |      117      |000|       0   | (id, flags, offset)
[20:34:36.104]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.104]   AT 01  : TaskName: CFW -- |  255  |    6  |    0x19ff     | (ttl, proto, chksum)
[20:34:36.109]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.109]   AT 01  : TaskName: CFW -- |   10  |  158  |  238  |  109  | (src)
[20:34:36.109]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.109]   AT 01  : TaskName: CFW -- |  107  |  191  |   60  |  141  | (dest)
[20:34:36.109]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:36.109]   AT 01  : TaskName: CFW -- ip4_output_if: call netif->output()
[20:34:36.109]   AT 01  : TaskName: CFW -- data_output ---------------------------------
[20:34:36.109]          : Fn 1097661 T1 0827 T2 19 T3 39 Time 00 06 08 730
[20:34:36.112]   AT 01  : TaskName: CFW -- State: ESTABLISHED
[20:34:36.112]          : Fn 1097673 T1 0827 T2 05 T3 00 Time 00 06 08 785
[20:34:36.112]   AT 01  : TaskName: Task Idle -- timer_sender handler=0x880e5e21,arg=0x0
[20:34:36.112]   AT 01  : TaskName: CFW -- sys_dotimeout handler=0x880e5e21,args=0x0
[20:34:36.174]   AT 01  : TaskName: CFW -- sys_timeout msecs=250,handler=0x880e5e21,arg=0x0
[20:34:36.174]          : Fn 1097689 T1 0827 T2 21 T3 16 Time 00 06 08 857
[20:34:36.282]   L1S 02 : Tx Dummy on Tn 5 TxP 0
[20:34:36.355]          : Fn 1097727 T1 0827 T2 07 T3 03 Time 00 06 09 036
[20:34:36.355]   AT 01  : TaskName: Task Idle -- timer_sender handler=0x880e5e21,arg=0x0
[20:34:36.355]   AT 01  : TaskName: CFW -- sys_dotimeout handler=0x880e5e21,args=0x0
[20:34:36.355]   AT 01  : TaskName: CFW -- tcp_slowtmr: processing active pcb
[20:34:36.457]   AT 01  : TaskName: CFW -- sys_timeout msecs=250,handler=0x880e5e21,arg=0x0
[20:34:36.565]          : Fn 1097773 T1 0827 T2 01 T3 49 Time 00 06 09 246
[20:34:36.565]   MM 09  : Dump : at 0x82088AA9 (5/5) : 64 f0 00 27 91
[20:34:36.565]   MM 09  : Dump : at 0x82088ABA (6/6) : 64 f0 00 27 91 01
[20:34:36.565]   MM 09  : Dump : at 0x82088A23 (6/6) : 64 f0 00 27 91 01
[20:34:36.565]   MM 09  : Dump : at 0x82088A35 (6/6) : 64 f0 00 27 91 01
[20:34:36.566]   MM 09  : Att 1, Service 0x82, NMO 2
[20:34:36.566]          : Fn 1097775 T1 0827 T2 03 T3 00 Time 00 06 09 249
[20:34:36.605]   PAL 12 : SynchChange[2500,118]
[20:34:36.605]          : Fn 1097782 T1 0827 T2 10 T3 07 Time 00 06 09 286
[20:34:36.605]   AT 01  : TaskName: Task Idle -- timer_sender handler=0x880e5e21,arg=0x0
[20:34:36.605]   AT 01  : TaskName: CFW -- sys_dotimeout handler=0x880e5e21,args=0x0
[20:34:36.703]   AT 01  : TaskName: CFW -- sys_timeout msecs=250,handler=0x880e5e21,arg=0x0
[20:34:36.832]          : Fn 1097832 T1 0827 T2 08 T3 06 Time 00 06 09 514
[20:34:36.859]   PAL 12 : SynchChange[3750,207]
[20:34:36.859]          : Fn 1097836 T1 0827 T2 12 T3 10 Time 00 06 09 537
[20:34:36.859]   AT 01  : TaskName: Task Idle -- timer_sender handler=0x880e5e21,arg=0x0
[20:34:36.859]   AT 01  : TaskName: CFW -- sys_dotimeout handler=0x880e5e21,args=0x0
[20:34:36.859]   AT 01  : TaskName: CFW -- tcp_slowtmr: processing active pcb
[20:34:36.859]   AT 01  : TaskName: CFW -- tcp_slowtmr: polling application
[20:34:36.859]   AT 01  : TaskName: CFW -- lwip_tcp_event conn=0x82124c94,lwip_event:4,pcb:0x8213a0a8
[20:34:36.859]   AT 01  : TaskName: CFW -- tcp_output: nothing to send (0x0)
[20:34:36.860]   AT 01  : TaskName: CFW -- tcp_output: snd_wnd 14656, cwnd 1748, wnd 1748, seg == NULL, ack 8310
[20:34:36.969]   AT 01  : TaskName: CFW -- sys_timeout msecs=250,handler=0x880e5e21,arg=0x0
[20:34:36.978]          : Fn 1097864 T1 0827 T2 14 T3 38 Time 00 06 09 661
[20:34:37.080]   PAL 12 : SynchChange[3750,213]
[20:34:37.107]          : Fn 1097890 T1 0827 T2 14 T3 13 Time 00 06 09 787
[20:34:37.107]   AT 01  : TaskName: Task Idle -- timer_sender handler=0x880e5e21,arg=0x0
[20:34:37.107]   AT 01  : TaskName: CFW -- sys_dotimeout handler=0x880e5e21,args=0x0
[20:34:37.156]   AT 01  : TaskName: CFW -- sys_timeout msecs=250,handler=0x880e5e21,arg=0x0
[20:34:37.156]          : Fn 1097903 T1 0827 T2 01 T3 26 Time 00 06 09 840
[20:34:37.267]   PAL 12 : SynchChange[4375,213]
[20:34:37.302]          : Fn 1097932 T1 0828 T2 04 T3 04 Time 00 06 09 980
[20:34:37.302]   AT 01  : TaskName: CFW -- pbuf_alloc(length=44)
[20:34:37.302]   AT 01  : TaskName: CFW -- pbuf_alloc(length=44) == 0x82169f88
[20:34:37.302]          : Detected event: 0x9db00000
[20:34:37.302]          : Detected event: 0x9db10000
[20:34:37.302]   AT 01  : TaskName: CFW -- tcpip_thread: PACKET 0x8211b408
[20:34:37.302]   AT 01  : TaskName: CFW -- ip_input: iphdr->dest 0x6dee9e0a netif->ip_addr 0x6dee9e0a (0x0, 0x0, 0x6dee9e0a)
[20:34:37.302]   AT 01  : TaskName: CFW -- ip4_input: packet accepted on interface GP
[20:34:37.302]   AT 01  : TaskName: CFW -- ip4_input:
[20:34:37.302]   AT 01  : TaskName: CFW -- IP header:
[20:34:37.307]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.307]   AT 01  : TaskName: CFW -- | 4 | 5 |  0x04 |        44     | (v, hl, tos, len)
[20:34:37.307]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.307]   AT 01  : TaskName: CFW -- |    17453      |010|       0   | (id, flags, offset)
[20:34:37.307]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.307]   AT 01  : TaskName: CFW -- |   46  |    6  |    0x6743     | (ttl, proto, chksum)
[20:34:37.307]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.314]   AT 01  : TaskName: CFW -- |  107  |  191  |   60  |  141  | (src)
[20:34:37.314]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.314]   AT 01  : TaskName: CFW -- |   10  |  158  |  238  |  109  | (dest)
[20:34:37.314]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.314]   AT 01  : TaskName: CFW -- ip4_input: p->len 44 p->tot_len 44
[20:34:37.314]   AT 01  : TaskName: CFW -- pbuf_header: old 0x82169f98 new 0x82169fac (-20)
[20:34:37.314]   AT 01  : TaskName: CFW -- TCP header:
[20:34:37.319]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.319]   AT 01  : TaskName: CFW -- |     1883      |    54911      | (src port, dest port)
[20:34:37.319]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.319]   AT 01  : TaskName: CFW -- |           3954207596          | (seq no)
[20:34:37.319]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.319]   AT 01  : TaskName: CFW -- |           0000008314          | (ack no)
[20:34:37.319]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.324]   AT 01  : TaskName: CFW -- |  5 |   |011000|       229     | (hdrlen, flags (
[20:34:37.324]   AT 01  : TaskName: CFW -- PSH
[20:34:37.324]   AT 01  : TaskName: CFW -- ACK
[20:34:37.324]   AT 01  : TaskName: CFW --
[20:34:37.324]   AT 01  : TaskName: CFW -- ), win)
[20:34:37.324]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.324]   AT 01  : TaskName: CFW -- |    0x47f3     |         0     | (chksum, urgp)
[20:34:37.324]   AT 01  : TaskName: CFW -- +-------------------------------+
[20:34:37.324]   AT 01  : TaskName: CFW -- inet_chksum_pseudo(): checksumming pbuf 0x82169f88 (has next 0x0)
[20:34:37.329]   AT 01  : TaskName: CFW -- inet_chksum_pseudo(): pbuf chain lwip_chksum()=ffff
[20:34:37.329]   AT 01  : TaskName: CFW -- pbuf_header: old 0x82169fac new 0x82169fc0 (-20)
[20:34:37.329]   AT 01  : TaskName: CFW -- +-+-+-+-+-+-+-+-+-+-+-+-+-+- tcp_input: flags
[20:34:37.329]   AT 01  : TaskName: CFW -- PSH
[20:34:37.329]   AT 01  : TaskName: CFW -- ACK
[20:34:37.329]   AT 01  : TaskName: CFW --
[20:34:37.329]   AT 01  : TaskName: CFW -- -+-+-+-+-+-+-+-+-+-+-+-+-+-+
[20:34:37.329]   AT 01  : TaskName: CFW -- State: ESTABLISHED
[20:34:37.329]   AT 01  : TaskName: CFW -- tcp_receive: window update 14656
[20:34:37.335]   AT 01  : TaskName: CFW -- tcp_receive: slow start cwnd 1752
[20:34:37.335]   AT 01  : TaskName: CFW -- tcp_receive: ACK for 8314, unacked->seqno 8310:8314
[20:34:37.335]   AT 01  : TaskName: CFW -- tcp_receive: removing 8310:8314 from pcb->unacked
[20:34:37.335]   AT 01  : TaskName: CFW -- tcp_receive: queuelen 1 ...
[20:34:37.335]   AT 01  : TaskName: CFW -- pbuf_free(0x82129698)
[20:34:37.335]   AT 01  : TaskName: CFW -- pbuf_free: deallocating 0x82129698
[20:34:37.335]   AT 01  : TaskName: CFW -- 0 (after freeing unacked)
[20:34:37.340]   AT 01  : TaskName: CFW -- tcp_receive: pcb->rttest 703 rtseq 8310 ackno 8314
[20:34:37.340]   AT 01  : TaskName: CFW -- tcp_receive: experienced rtt 2 ticks (1000 msec).
[20:34:37.340]   AT 01  : TaskName: CFW -- tcp_receive: RTO 8 (4000 milliseconds)
[20:34:37.340]   AT 01  : TaskName: CFW -- lwip_tcp_event conn=0x82124c94,lwip_event:1,pcb:0x8213a0a8
[20:34:37.340]   AT 01  : TaskName: CFW -- tcp_recved: received 4 bytes, wnd 23040 (0).
[20:34:37.340]   AT 01  : TaskName: CFW -- mqtt_parse_incoming: Remaining length after fixed header: 2
[20:34:37.340]   AT 01  : TaskName: CFW -- mqtt_parse_incoming: msg_idx: 4, cpy_len: 2, remaining 0
[20:34:37.438]   AT 01  : TaskName: CFW -- mqtt_message_received: PUBCOMP response with id 36

**Comment by Neutree** [comment]
https://github.com/Ai-Thinker-Open/GPRS_C_SDK/releases/tag/V1.404
